<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Cortex.Cryptography.Bls" Version="0.4.0" />
    <PackageReference Include="CryptSharp" Version="1.3.0" />
    <PackageReference Include="NStratis.HashLib" Version="1.0.0.1" />
    <PackageReference Include="Scrypt.NET" Version="1.3.0" />
    <PackageReference Include="SimpleBase" Version="5.4.1" />
    <PackageReference Include="Thirdweb" Version="2.25.1" />
  </ItemGroup>

</Project>
